#!/bin/bash

# sxhkd hotkeys
pgrep -x sxhkd > /dev/null || sxhkd &

# bspc configuration 

bspc monitor -d 0 1 2 3 4 5 6 7 8 9 

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true
bspc config border_width        3
bspc config left_padding        4
bspc config right_padding       4
bspc config window_gap          6

bspc config focused_border_color "#1F8999"
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config ignore_ewmh_focus    true 

bspc rule -a eww-bar layer=above state=floating urgent=on sticky=on
bspc rule -a eww-bar-eventbox layer=above state=floating urgent=on sticky=on
bspc rule -a Simics desktop=^8 follow=off state=floating
bspc rule -a firefox focus=off desktop=^2 
bspc rule -a Chromium focus=off desktop=^2 
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pavucontrol state=floating


# X11 Compositor
picom -b &

# Eww top bar
pkill eww

eww d &

eww open bar

eww open pollvars 



