#!/bin/sh

signal=$1


open_calendar() {
    eww open calendar
    eww update calendar_reveal="true"
    eww update system_reveal="false"
    sleep 0.4
    eww close system
}

close_calendar() {
    eww update calendar_reveal="false"
    sleep 0.4
    eww close calendar
}

open_system() {
    eww open system
    eww update system_reveal="true"
    eww update calendar_reveal="false"
    sleep 0.4
    eww close calendar
}

close_system() {
    eww update system_reveal="false"
    sleep 0.4
    eww close system
}


if [ $signal = "--bar-on" ]; then

    xdo raise -N "eww-bar"
    eww update bar_reveal="true"
    
    # bspc config top_padding 35
    

elif [ $signal = "--bar-off" ]; then

    status1=$(eww get calendar_reveal)
    status2=$(eww get system_reveal)

    if [ $status1 = "true" ] || [ $status2 = "true" ]; then
        exec ./scripts/delay_bar_exit
    fi

    # bspc config top_padding 0
    eww update bar_reveal="false"
    eww update system_reveal="false"
    eww update calendar_reveal="false"
    sleep 0.4
    xdo lower -N "eww-bar"
    eww close calendar
    eww close system


elif [ $signal = "--calendar-on" ]; then

    status=$(eww get calendar_reveal)
    if [ $status = "true" ]; then
        close_calendar
    else
        open_calendar
    fi
    

elif [ $signal = "--calendar-off" ]; then

    close_calendar

elif [ $signal = "--system-on" ]; then

    status=$(eww get system_reveal)
    if [ $status = "true" ]; then
        close_system
    else
        open_system
    fi
    

elif [ $signal = "--system-off" ]; then

    close_system

fi