#!/bin/bash

status=$(nmcli g | grep -oE "connected")
essid=$(nmcli c | head -n 2 | tail -n 1 | cut -d" " -f 1)
type=$(nmcli c | head -n 2 | tail -n 1 | awk '{$1=$1;print}' | rev | cut -d" " -f 2 | rev)
if [ $type = "ethernet" ] ; then
    icon="󰖟"
    text="LAN"
    col="#a1bdce"
elif [ $type = "wifi" ] ; then
    icon=""
    text="${essid}"
    col="#a1bdce"
else
    icon="󰪎"
    text=""
    col="#575268"
fi



if [[ "$1" == "--COL" ]]; then
    echo $col	
elif [[ "$1" == "--ESSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi

