#!/bin/sh

BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`

status=`cat /sys/class/power_supply/${BAT}/status`
charge=`cat /sys/class/power_supply/${BAT}/capacity`


battery_exists() {
	BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
	if [ -z $BAT ]; then
		eww update has_battery=false
	else
		eww update has_battery=true
	fi
}

bat_alert() {
	if [ $status == "Discharging" ]; then
		warning_20_fired=`eww get battery_warning_20_fired`
		warning_40_fired=`eww get battery_warning_40_fired`

		if [ $warning_40_fired == "false" ] && [ $charge -le "40" ]; then
			notify-send -u critical -t 0 "Battery" \
				-h "string:wired-note:battery" \
				-h "string:wired-tag:indicator" \
				-h int:value:40 \
				--hint=string:image-path:$HOME/.config/eww/img/battery-beige.svg
			eww update battery_warning_40_fired="true"
		elif [ $warning_20_fired == "false" ] && [ $charge -le "20" ]; then
			notify-send -u critical -t 0 "Battery" \
				-h "string:wired-note:battery" \
				-h "string:wired-tag:indicator" \
				-h int:value:20 \
				--hint=string:image-path:$HOME/.config/eww/img/battery-beige.svg
			eww update battery_warning_20_fired="true"
		fi

	else
		eww update battery_warning_20_fired="false"
		eww update battery_warning_40_fired="false"
	fi
}

if [[ "$1" == "--bat-exists" ]]; then
	battery_exists
elif [[ "$1" == "--bat-alert" ]]; then
	bat_alert
fi



