#!/bin/sh

BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`

status=`cat /sys/class/power_supply/${BAT}/status`
charge=`cat /sys/class/power_supply/${BAT}/capacity`


battery_exists() {
	BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
	if [ -z $BAT ]; then
		eww update has_battery=false
	else
		eww update has_battery=true
	fi
}

if [[ "$1" == "--bat" ]]; then
	echo $charge
elif [[ "$1" == "--bat-st" ]]; then
	echo $status
elif [[ "$1" == "--bat-exists" ]]; then
	battery_exists
fi


if [ $status == "Discharging" ]; then
	warning_20_fired=`eww get battery_warning_20_fired`
	warning_40_fired=`eww get battery_warning_40_fired`

	if [ $warning_40_fired == "false" ] && [ $charge -le "40" ]; then
		./scripts/toggle_fade --battery-warning-on &
		eww update battery_warning_40_fired="true"
	elif [ $warning_20_fired == "false" ] && [ $charge -le "20" ]; then
		./scripts/toggle_fade --battery-warning-on &
		eww update battery_warning_20_fired="true"
	fi

else
	eww update battery_warning_20_fired="false"
	eww update battery_warning_40_fired="false"
fi
