#!/bin/sh



battery() {
	BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
	cat /sys/class/power_supply/${BAT}/capacity
}
battery_stat() {
	BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
	cat /sys/class/power_supply/${BAT}/status
}
battery_exists() {
	BAT=`ls /sys/class/power_supply | grep BAT | head -n 1`
	if [ -z $BAT ]; then
		eww update has_battery=false
	else
		eww update has_battery=true
	fi
}

if [[ "$1" == "--bat" ]]; then
	battery
elif [[ "$1" == "--bat-st" ]]; then
	battery_stat
elif [[ "$1" == "--bat-exists" ]]; then
	battery_exists
fi
