#!/bin/sh

./scripts/battery --bat-exists &

# X11 Compositor
picom -b &

# Wallpaper
pkill feh
feh -F --bg-scale ~/.config/eww/background.jpg &

# System tray
pkill trayer
trayer --edge top --align center --widthtype percent --width 10 --padding 5 --distance 11 --tint 000000 --alpha 21 --transparent true --iconspacing 2 & 

# vpn tray
pkill nm-applet
nm-applet &

# bluman bluetooth
pkill blueman-applet
blueman-applet &

# cursor fix
xsetroot -cursor_name left_ptr

# autorandr refresh
autorandr -c --ignore-lid & 

# fix for a gap caused by a restart
sleep 0.25
bspc config top_padding 40

#runst notifications
pkill runst
{ sleep 4; runst; } &
