#!/bin/sh

signal=$1


open_battery_warning() {
    
    eww open battery_warning
    xdo raise -a "Eww - battery_warning"
    eww update battery_warning_reveal="true"
    sleep 5
    eww update battery_warning_reveal="false"
    sleep 0.4
    eww close battery_warning
}


open_calendar() {
    eww open calendar
    eww update calendar_reveal="true"
    eww update system_reveal="false"
    sleep 0.4
    eww close system
}

close_calendar() {
    eww update calendar_reveal="false"
    sleep 0.4
    eww close calendar
}

open_system() {
    eww open system
    eww update system_reveal="true"
    eww update calendar_reveal="false"
    sleep 0.4
    eww close calendar
}

close_system() {
    eww update system_reveal="false"
    sleep 0.4
    eww close system
}


if [ $signal = "--calendar-on" ]; then

    status=$(eww get calendar_reveal)
    if [ $status = "true" ]; then
        close_calendar
    else
        open_calendar
    fi
    

elif [ $signal = "--calendar-off" ]; then

    close_calendar

elif [ $signal = "--system-on" ]; then

    status=$(eww get system_reveal)
    if [ $status = "true" ]; then
        close_system
    else
        open_system
    fi
    

elif [ $signal = "--system-off" ]; then

    close_system

elif [ $signal = "--battery-warning-on" ]; then

    open_battery_warning

fi