#!/bin/sh

if [[ "$1" == "--up" ]]; then
    amixer  -M sset Master 5%+
elif [[ "$1" == "--down" ]]; then
	eval amixer  sset Master 5%-
fi

volume=`./scripts/volume_get_update`

eww update volume="$volume"

if [ $volume != "0" ]; then
    eww update vol_reveal="true"
fi

