#!/bin/sh

status=$(nmcli g | grep -oE "connected")
essid=$(nmcli c | grep wlp2s0 | awk '{print ($1)}')

if [ -z $status ] ; then
    icon=""
    text=""
    col="#575268"
    echo ""

elif [ $essid ] ; then
    icon=""
    text="${essid}"
    col="#a1bdce"
    echo ""
else
    icon=""
    text="LAN"
    col="#a1bdce"
    echo ""
fi

echo $icon
echo $essid
echo $col


if [[ "$1" == "--COL" ]]; then
    echo $col	
elif [[ "$1" == "--ESSID" ]]; then
	echo $text
elif [[ "$1" == "--ICON" ]]; then
	echo $icon
fi

